export const FeaturedProducts = [
  {
    productId: "1001",
    productName: "Wireless Bluetooth Headphones",
    image: "/images/product/product-1.jpeg",
    price: 59.99,
    actualPrice: 79.99,
    discountedPrice: 59.99,
    categoryName: "Electronics",
    rating: 4.5,
  },
  {
    productId: "1002",
    productName: "Smartwatch with Heart Rate Monitor",
    image: "/images/product/product-2.jpeg",
    price: 199.99,
    actualPrice: 249.99,
    discountedPrice: 199.99,
    categoryName: "Electronics",
    rating: 4.7,
  },
  {
    productId: "1003",
    productName: "4K Ultra HD TV",
    image: "/images/product/product-3.jpeg",
    price: 499.99,
    actualPrice: 599.99,
    discountedPrice: 499.99,
    categoryName: "Electronics",
    rating: 4.6,
  },
  {
    productId: "1004",
    productName: "Portable Charger",
    image: "/images/product/product-4.jpeg",
    price: 29.99,
    actualPrice: 39.99,
    discountedPrice: 29.99,
    categoryName: "Electronics",
    rating: 4.4,
  },
  {
    productId: "1005",
    productName: "Gaming Mouse",
    image: "/images/product/product-5.jpeg",
    price: 49.99,
    actualPrice: 69.99,
    discountedPrice: 49.99,
    categoryName: "Electronics",
    rating: 4.8,
  },
  {
    productId: "1006",
    productName: "Ergonomic Office Chair",
    image: "/images/product/product-6.jpeg",
    price: 149.99,
    actualPrice: 179.99,
    discountedPrice: 149.99,
    categoryName: "Furniture",
    rating: 4.3,
  },
  {
    productId: "1007",
    productName: "LED Desk Lamp",
    image: "/images/product/product-7.jpeg",
    price: 39.99,
    actualPrice: 49.99,
    discountedPrice: 39.99,
    categoryName: "Furniture",
    rating: 4.6,
  },
  {
    productId: "1008",
    productName: "Yoga Mat",
    image: "/images/product/product-8.jpeg",
    price: 24.99,
    actualPrice: 34.99,
    discountedPrice: 24.99,
    categoryName: "Fitness",
    rating: 4.5,
  },
  {
    productId: "1009",
    productName: "Protein Powder",
    image: "/images/product/product-9.jpeg",
    price: 39.99,
    actualPrice: 49.99,
    discountedPrice: 39.99,
    categoryName: "Health",
    rating: 4.7,
  },
  {
    productId: "1010",
    productName: "Water Bottle",
    image: "/images/product/product-10.jpeg",
    price: 19.99,
    actualPrice: 24.99,
    discountedPrice: 19.99,
    categoryName: "Fitness",
    rating: 4.4,
  }
];
